server:
  port: 8888
spring:
  profiles:
#    select a native EnvironmentRepository rather than a Git EnvironmentRepository
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wuxii/config-repo
          basedir: ${user.home}/git/config-repo
#        bootstrap: true
        native:
          # for windows file:///
          search-locations: file:///${user.parent.dir}/config-repo