debug: true
server:
  port: 9000
spring:
  application:
    name: zuul-gateway
zuul:
  routes:
    movie:
      path: /movie/**
      service-id: movie
    member:
      path: /member/**
#ribbon: # ribbon global setting
#    ReadTimeout: 10000
#    ConnectionTimeout: 5000
#movie: # ribbon setting by service-id
#  ribbon:
#    ReadTimeout: 5000
#    ConnectionTimeout: 5000
