package org.harmony.test.cxf.wsdl2java;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-08-18T15:18:03.656+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://www.harmony.com/simple", name = "Simple")
public interface Simple {

    @RequestWrapper(localName = "sayHi", targetNamespace = "http://www.harmony.com/simple", className = "org.harmony.test.cxf.wsdl2java.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://www.harmony.com/simple", className = "org.harmony.test.cxf.wsdl2java.SayHiResponse")
    @WebMethod(operationName = "sayHi")
    public Response<org.harmony.test.cxf.wsdl2java.SayHiResponse> sayHiAsync(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @RequestWrapper(localName = "sayHi", targetNamespace = "http://www.harmony.com/simple", className = "org.harmony.test.cxf.wsdl2java.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://www.harmony.com/simple", className = "org.harmony.test.cxf.wsdl2java.SayHiResponse")
    @WebMethod(operationName = "sayHi")
    public Future<?> sayHiAsync(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<org.harmony.test.cxf.wsdl2java.SayHiResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://www.harmony.com/simple", className = "org.harmony.test.cxf.wsdl2java.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://www.harmony.com/simple", className = "org.harmony.test.cxf.wsdl2java.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
