#debug: true
server:
  port: 0
spring:
  application:
    name: movie
  sleuth:
    sampler:
      probability: 1.0
#    messaging:
#      kafka:
#        enabled: true
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka
#feign: # see MemberClient
#  client:
#    config:
#      default # global setting
#       connectionTimeout: 5000
#      member:
#        connectionTimeout: 5000